name: linting, testing, building
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    pipeline:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build:prod

            - name: Lint TypeScript
              run: npm run lint:ts

            - name: Lint SCSS
              run: npm run lint:scss

            - name: Unit tests
              run: npm run test:unit

            - name: Build Storybook
              run: npm run storybook:build

            - name: Prepare for screenshot tests
              run: |
                  mkdir -p .loki/reference
                  # Копируем эталонные скриншоты если они есть в репозитории
                  [ -d loki/reference ] && cp -r loki/reference .loki/ || true

            - name: Run Loki tests
              run: npm run test:ui:ci

            - name: Upload differences if failed
              if: failure()
              uses: actions/upload-artifact@v2
              with:
                  name: loki-differences
                  path: .loki/difference