name: linting, testing, building

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    pipeline:
        timeout-minutes: 10
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 22.x ]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Install system fonts
              run: |
                  sudo apt-get update
                  sudo apt-get install -y fonts-dejavu-core fonts-dejavu fonts-liberation fontconfig

            - name: Check font installed
              run: fc-list | grep "DejaVu Sans Mono" || true

            - name: Build production project
              run: npm run build:prod

            - name: Lint TypeScript
              run: npm run lint:ts

            - name: Lint SCSS
              run: npm run lint:scss

            - name: Run unit tests
              run: npm run test:unit

            - name: Build Storybook for visual regression
              run: npm run storybook:build

            - name: Run Loki visual regression tests
              env:
                  DEBUG: "loki"
                  CHROMIUM_FLAGS: --no-sandbox --disable-gpu --disable-dev-shm-usage
                  LOKI_CHROMIUM_SANDBOX_DISABLED: "true"
              run: npm run test:ui:ci

            - name: Upload failed visual snapshots
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: loki-failed-snapshots
                  path: .loki
