name: linting, testing, building

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    pipeline:
        runs-on: windows-2022
        timeout-minutes: 10
        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v2

            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Build prod
              run: npm run build:prod
              if: always()

            - name: Lint TypeScript
              run: npm run lint:ts
              if: always()

            - name: Lint SCSS
              run: npm run lint:scss
              if: always()

            - name: Run unit tests
              run: npm run test:unit
              if: always()

            - name: Build Storybook
              run: npm run storybook:build
              if: always()

            - name: Run screenshot tests
              env:
                  DEBUG: "loki"
                  CHROMIUM_FLAGS: --no-sandbox --disable-gpu --disable-dev-shm-usage
                  LOKI_CHROMIUM_SANDBOX_DISABLED: "true"
              run: npm run test:ui:ci
              if: always()

            - name: Debug - list .loki files

              if: failure()
              run: |
                  echo "Contents of .loki:"
                  ls -R .loki || echo "No .loki directory found"

            - name: Upload Loki screenshot diffs
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: loki-diffs
                  path: .loki/difference
            - name: Upload Loki screenshot ref
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: loki-refs
                  path: .loki/reference
            - name: Upload Loki screenshot cur
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: loki-curs
                  path: .loki/current