name: linting, testing, building

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    pipeline:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v2

            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Install system fonts (Consolas)
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends fontconfig
                  echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
                  sudo apt-get install -y --no-install-recommends ttf-mscorefonts-installer
                  sudo fc-cache -f -v

            - name: Verify Consolas installed
              run: fc-list | grep "Consolas" || true
            - name: Build project
              run: npm run build:prod

            - name: Lint TypeScript
              run: npm run lint:ts

            - name: Lint SCSS
              run: npm run lint:scss

            - name: Run unit tests
              run: npm run test:unit

            - name: Build Storybook
              run: npm run storybook:build

            - name: Run screenshot tests
              env:
                  DEBUG: "loki"
                  CHROMIUM_FLAGS: --no-sandbox --disable-gpu --disable-dev-shm-usage
                  LOKI_CHROMIUM_SANDBOX_DISABLED: "true"
              run: npm run test:ui:ci

            - name: Debug - list .loki files

              if: failure()
              run: |
                  echo "Contents of .loki:"
                  ls -R .loki || echo "No .loki directory found"

            - name: Upload Loki screenshot diffs
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: loki-diffs
                  path: .loki/difference
            - name: Upload Loki screenshot ref
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: loki-refs
                  path: .loki/reference
            - name: Upload Loki screenshot cur
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: loki-curs
                  path: .loki/current